version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/rails_development
      - TEST_DATABASE_URL=postgres://postgres:postgres@db:5432/rails_test
    depends_on:
      - db
    network_mode: service:db
    user: vscode
  
  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rails_development
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

volumes:
  postgres-data:
